2025-03-06 11:50:41,098 - DEBUG - Sending seeders request to tracker
2025-03-06 11:50:41,114 - DEBUG - Seeders response: ['SEEDERS', '196.47.199.219:7000']
2025-03-06 11:50:41,114 - INFO - Attempting to download from seeder: 196.47.199.219:7000
2025-03-06 11:50:41,114 - DEBUG - Attempting to connect to seeder: ('196.47.199.219', 7000)
2025-03-06 11:50:41,114 - INFO - Connected to seeder ('196.47.199.219', 7000)
2025-03-06 11:50:41,114 - DEBUG - Requesting chunk count
2025-03-06 11:50:41,129 - INFO - Total chunks: 1
2025-03-06 11:50:41,129 - DEBUG - Downloading chunk 0
2025-03-06 11:50:41,129 - WARNING - Chunk 0 download retry 1: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-06 11:50:43,141 - WARNING - Chunk 0 download retry 2: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-06 11:50:45,141 - WARNING - Chunk 0 download retry 3: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-06 11:50:45,141 - ERROR - Failed to download chunk 0: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-06 11:50:45,141 - ERROR - Traceback (most recent call last):
  File "C:\Users\27677\OneDrive - University of Cape Town\Documents\CSC3002F\network_app\torrent\leecher.py", line 93, in download_from_seeder
    chunk = tcp_client.recv(CHUNK_SIZE)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

2025-03-06 11:50:45,141 - ERROR - Download error from 196.47.199.219:7000: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-06 11:50:45,141 - ERROR - Traceback (most recent call last):
  File "C:\Users\27677\OneDrive - University of Cape Town\Documents\CSC3002F\network_app\torrent\leecher.py", line 93, in download_from_seeder
    chunk = tcp_client.recv(CHUNK_SIZE)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

2025-03-06 11:50:45,141 - ERROR - Failed to download file from all seeders.
2025-03-06 11:57:02,987 - DEBUG - Sending seeders request to tracker
2025-03-06 11:57:03,004 - DEBUG - Seeders response: ['SEEDERS', '196.47.199.219:7000']
2025-03-06 11:57:03,004 - INFO - Attempting to download from seeder: 196.47.199.219:7000
2025-03-06 11:57:03,005 - DEBUG - Attempting to connect to seeder: ('196.47.199.219', 7000)
2025-03-06 11:57:03,005 - INFO - Connected to seeder ('196.47.199.219', 7000)
2025-03-06 11:57:03,006 - DEBUG - Requesting chunk count
2025-03-06 11:57:03,008 - INFO - Total chunks: 1
2025-03-06 11:57:03,008 - DEBUG - Downloading chunk 0
2025-03-06 11:57:03,036 - DEBUG - Successfully downloaded chunk 0 (19 bytes)
2025-03-06 11:57:03,037 - INFO - File sample.txt downloaded successfully.
2025-03-06 13:45:53,654 - DEBUG - Sending seeders request to tracker
2025-03-06 13:45:53,775 - DEBUG - Seeders response: ['SEEDERS', '196.47.199.219:7000']
2025-03-06 13:45:53,775 - INFO - Attempting to download from seeder: 196.47.199.219:7000
2025-03-06 13:45:53,788 - DEBUG - Attempting to connect to seeder: ('196.47.199.219', 7000)
2025-03-06 13:45:53,812 - INFO - Connected to seeder ('196.47.199.219', 7000)
2025-03-06 13:45:53,814 - DEBUG - Requesting chunk count
2025-03-06 13:45:54,229 - INFO - Total chunks: 1
2025-03-06 13:45:54,229 - DEBUG - Downloading chunk 0
2025-03-06 13:45:54,259 - DEBUG - Successfully downloaded chunk 0 (19 bytes)
2025-03-06 13:45:54,261 - INFO - File sample.txt downloaded successfully.
2025-03-06 13:48:12,506 - DEBUG - Sending seeders request to tracker
2025-03-06 13:48:12,525 - DEBUG - Seeders response: ['SEEDERS', '196.47.199.219:7000']
2025-03-06 13:48:12,526 - INFO - Attempting to download from seeder: 196.47.199.219:7000
2025-03-06 13:48:12,526 - DEBUG - Attempting to connect to seeder: ('196.47.199.219', 7000)
2025-03-06 13:48:12,527 - INFO - Connected to seeder ('196.47.199.219', 7000)
2025-03-06 13:48:12,527 - DEBUG - Requesting chunk count
2025-03-06 13:48:12,529 - INFO - Total chunks: 1
2025-03-06 13:48:12,531 - DEBUG - Downloading chunk 0
2025-03-06 13:48:12,548 - DEBUG - Successfully downloaded chunk 0 (19 bytes)
2025-03-06 13:48:12,549 - INFO - File sample.txt downloaded successfully.
2025-03-11 14:46:25,434 - DEBUG - Sending seeders request to tracker
2025-03-11 14:46:25,461 - DEBUG - Seeders response: ['NO_SEEDERS']
2025-03-11 14:46:25,461 - ERROR - No seeders available.
2025-03-11 14:46:25,461 - ERROR - No seeders found.
2025-03-11 21:45:38,398 - DEBUG - Sending seeders request to tracker
2025-03-11 21:45:38,528 - DEBUG - Seeders response: ['SEEDERS', '192.168.0.214:7000:21']
2025-03-11 21:45:38,528 - INFO - Attempting to download first two chunks from seeder: 192.168.0.214:7000:21
2025-03-11 21:45:38,529 - ERROR - Download error from 192.168.0.214:7000:21: too many values to unpack (expected 2)
2025-03-11 21:45:38,561 - ERROR - Traceback (most recent call last):
  File "C:\Users\27677\OneDrive - University of Cape Town\Documents\CSC3002F\network_app\torrent\leecher.py", line 56, in download_first_two_chunks
    ip, port = seeder_addr.split(":")
ValueError: too many values to unpack (expected 2)

2025-03-11 21:45:38,562 - ERROR - Failed to download chunks from seeder.
2025-03-11 21:49:17,479 - DEBUG - Sending seeders request to tracker
2025-03-11 21:49:17,533 - DEBUG - Seeders response: ['SEEDERS', '192.168.0.214:7000:21']
2025-03-11 21:49:17,533 - INFO - Attempting to download first two chunks from seeder: 192.168.0.214:7000 (has 21 chunks)
2025-03-11 21:49:17,557 - DEBUG - Attempting to connect to seeder: ('192.168.0.214', 7000)
2025-03-11 21:49:17,569 - INFO - Connected to seeder ('192.168.0.214', 7000)
2025-03-11 21:49:17,682 - INFO - Total chunks: 21
2025-03-11 21:49:17,903 - DEBUG - Successfully downloaded chunk 0 (524288 bytes)
2025-03-11 21:49:17,905 - ERROR - Download error from 192.168.0.214:7000: No data received for chunk
2025-03-11 21:49:17,906 - ERROR - Traceback (most recent call last):
  File "C:\Users\27677\OneDrive - University of Cape Town\Documents\CSC3002F\network_app\torrent\leecher.py", line 125, in download_first_two_chunks
    raise ValueError("No data received for chunk")
ValueError: No data received for chunk

2025-03-11 21:49:17,906 - ERROR - Failed to download chunks from seeder.
2025-03-11 21:53:29,741 - DEBUG - Sending seeders request to tracker
2025-03-11 21:53:29,784 - DEBUG - Seeders response: ['SEEDERS', '192.168.0.214:7000:21']
2025-03-11 21:53:29,784 - INFO - Attempting to download chunks from seeder: 192.168.0.214:7000 (has 21 chunks)
2025-03-11 21:53:29,785 - DEBUG - Attempting to connect to seeder: ('192.168.0.214', 7000)
2025-03-11 21:53:29,786 - INFO - Connected to seeder ('192.168.0.214', 7000)
2025-03-11 21:53:29,788 - INFO - Total chunks: 21
2025-03-11 21:53:29,800 - DEBUG - Successfully downloaded chunk 0 (524288 bytes)
2025-03-11 21:53:29,818 - DEBUG - Successfully downloaded chunk 1 (524288 bytes)
2025-03-11 21:53:29,820 - INFO - Downloaded 2 chunks of large_text_file.txt successfully.
